---------------------------
--New TABLE
--BUP_MIM_POS_FLIGHT
---------------------------
  CREATE TABLE "RPT_VIEW_USER_RIS"."BUP_MIM_POS_FLIGHT" 
   (	"BUP_CODE_SELLER" VARCHAR2(3),
	"BUP_SUBCODE_SELLER" NUMBER(1,0),
	"SHOP" VARCHAR2(10),
	"POS" VARCHAR2(10),
	"RECEIPT" VARCHAR2(20),
	"SALE_DATE" DATE,
	"SALE_TIME" NUMBER(4,0),
	"PREFIX" VARCHAR2(3 CHAR),
	"SUFFIX" VARCHAR2(5 CHAR),
	"DESTINATION_IATA" VARCHAR2(3 CHAR),
	"FINAL_DESTINATION_IATA" VARCHAR2(3 CHAR),
	"GATE_CODE" VARCHAR2(3 CHAR),
	"PASSENGER_CLASS" VARCHAR2(5 CHAR),
	"EU_NEU_CODE" VARCHAR2(3 CHAR),
	"ARRIVAL_DEPARTURE" VARCHAR2(1 CHAR),
	"ROW_NUMBER" NUMBER,
	"FILE_NAME" VARCHAR2(20),
	"VERSION_NUMBER" VARCHAR2(10),
	"ID" NUMBER,
	"DATE_CREATED" DATE,
	"DATE_UPDATED" DATE,
	"DATE_DELETED" DATE,
	"AUD_ID_CREATED" NUMBER,
	"AUD_ID_UPDATED" NUMBER,
	"AUD_ID_DELETED" NUMBER,
	"CURR_ID" CHAR(1)
   );
