---------------------------
--New TABLE
--BUP_WOD_POS_FLIGHT
---------------------------
  CREATE TABLE "RPT_VIEW_USER_RIS"."BUP_WOD_POS_FLIGHT" 
   (	"BUP_CODE_SELLER" VARCHAR2(3 CHAR),
	"BUP_SUBCODE_SELLER" VARCHAR2(1 CHAR),
	"SHOP" VARCHAR2(10 CHAR),
	"POS" VARCHAR2(10 CHAR),
	"RECEIPT" VARCHAR2(20 CHAR),
	"SALE_DATE" DATE,
	"SALE_TIME" NUMBER,
	"PREFIX" VARCHAR2(3 CHAR),
	"SUFFIX" VARCHAR2(5 CHAR),
	"DESTINATION_IATA" VARCHAR2(3 CHAR),
	"FINAL_DESTINATION_IATA" VARCHAR2(3 CHAR),
	"GATE_CODE" VARCHAR2(3 CHAR),
	"PASSENGER_CLASS" VARCHAR2(5 CHAR),
	"EU_NEU_CODE" VARCHAR2(3 CHAR),
	"ARRIVAL_DEPARTURE" VARCHAR2(1 CHAR),
	"ROW_NUMBER" NUMBER,
	"FILE_NAME" VARCHAR2(111 CHAR),
	"VERSION_NUMBER" VARCHAR2(20 CHAR),
	"AUD_ID" NUMBER,
	"ID" NUMBER,
	"DATE_CREATED" DATE,
	"DATE_UPDATED" DATE,
	"DATE_DELETED" DATE,
	"AUD_ID_CREATED" NUMBER,
	"AUD_ID_UPDATED" NUMBER,
	"AUD_ID_DELETED" NUMBER,
	"CURR_ID" VARCHAR2(1 CHAR)
   );
  COMMENT ON TABLE "RPT_VIEW_USER_RIS"."BUP_WOD_POS_FLIGHT" IS 'Version 1.00.50';
