---------------------------
--New TABLE
--MD_BUP_WHS_AMOUNTS
---------------------------
  CREATE TABLE "RPT_VIEW_USER_RIS"."MD_BUP_WHS_AMOUNTS" 
   (	"BUP_CODE_SELLER" VARCHAR2(3 CHAR),
	"BUP_SUBCODE_SELLER" VARCHAR2(1 CHAR),
	"FILE_NAME" VARCHAR2(100 CHAR),
	"SALE_DATE" DATE,
	"CHECK_DATE" DATE,
	"LI_NUMBER_OF_ITEM_LINES" NUMBER,
	"LI_NUMBER_OF_ARTICLES" NUMBER,
	"LI_TOTAL_NET_AMOUNT" NUMBER,
	"LI_TOTAL_GROSS_AMOUNT" NUMBER,
	"LI_TOTAL_TAX_AMOUNT" NUMBER,
	"LI_TOTAL_DISCOUNT_AMOUNT" NUMBER,
	"PT_TOTAL_AMOUNT" NUMBER,
	"PT_TOTAL_VOUCHER_AMOUNT" NUMBER,
	"PT_NR_VOUCHERS" NUMBER,
	"LI_NR_RECEIPTS" NUMBER,
	"PT_NR_RECEIPTS" NUMBER,
	"PAYMENT_NO_LINE_ITEMS" NUMBER,
	"LINE_ITEMS_NO_PAYMENT" NUMBER,
	"MULTIPLE_PAYMENTLINES" NUMBER,
	"ID" NUMBER,
	"DATE_CREATED" DATE,
	"DATE_UPDATED" DATE,
	"DATE_DELETED" DATE,
	"AUD_ID_CREATED" NUMBER,
	"AUD_ID_UPDATED" NUMBER,
	"AUD_ID_DELETED" NUMBER,
	"CURR_ID" VARCHAR2(1 CHAR)
   );
  COMMENT ON TABLE "RPT_VIEW_USER_RIS"."MD_BUP_WHS_AMOUNTS" IS 'Version 2019-41';
