---------------------------
--New TABLE
--MD_BUP_FILE_DELIVERY
---------------------------
  CREATE TABLE "RPT_VIEW_USER_RIS"."MD_BUP_FILE_DELIVERY" 
   (	"BUSINESS_PARTNER" VARCHAR2(3 CHAR) NOT NULL ENABLE,
	"START_DELIVERY" DATE NOT NULL ENABLE,
	"DELIVERY_TIME" VARCHAR2(5 CHAR) NOT NULL ENABLE,
	"END_DELIVERY" DATE,
	"DATE_CREATED" DATE NOT NULL ENABLE,
	"DATE_UPDATED" DATE,
	"DATE_DELETED" DATE,
	"CURR_ID" VARCHAR2(1 CHAR) NOT NULL ENABLE
   );
